services:
  - type: web
    name: autodialer
    runtime: docker
    dockerfilePath: backoffice/server/Dockerfile
    dockerContext: backoffice/server
    envVars:
      - key: NODE_ENV
        value: production
