services:
  - type: web
    name: autodialer
    runtime: node
    rootDir: backoffice/server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
